href:
  news: https://news.railstutorial.org/
  rails_tutorial: https://www.railstutorial.org/
  author: https://www.michaelhartl.com/
  learn: https://www.learnenough.com/
  book: https://www.railstutorial.org/book
  screencast: https://screencasts.railstutorial.org/
  rails: https://rubyonrails.org/"
  contact: https://www.railstutorial.org/contact
  help: https://www.railstutorial.org/help

digits:
  length_name_max_50: 50
  length_email_max_255: 255
  length_password_min_6: 6

regex:
  email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/'
